
Metrics/CyclomaticComplexity:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Lint/Void:
  Enabled: false

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Gemspec/DevelopmentDependencies:
  Enabled: true

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
