# This is the RuboCop configuration file.
# It contains the rules and settings for the RuboCop linter.
#
# Enable/disable the cops individually.
# For more information, refer to the RuboCop documentation.
#
# https://docs.rubocop.org/rubocop/cops.html
#
require:
  - rubocop-performance

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Lint/Void:
  Enabled: true

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Gemspec/DevelopmentDependencies:
  Enabled: true

AllCops:
  NewCops: enable
  UseCache: true
  MaxFilesInCache: 100
  TargetRubyVersion: 3.0

Metrics/ModuleLength:
    Enabled: true
    Max: 250
    CountAsOne: ['method_call']

Metrics/MethodLength:
  Enabled: true
  Max: 30
  CountAsOne: ['method_call']

Metrics/AbcSize:
  Enabled: true
  Max: 20

Performance/Size:
  Exclude:
  #   - lib/example.rb

Style/NegatedIfElseCondition:
  Enabled: true
  EnforcedStyle: both
