
Metrics/CyclomaticComplexity:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Lint/Void:
  Enabled: true

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Gemspec/DevelopmentDependencies:
  Enabled: true

AllCops:
  NewCops: enable
  UseCache: true
  MaxFilesInCache: 100
  TargetRubyVersion: 3.0

Metrics/ModuleLength:
    Enabled: true
    Max: 250
    CountAsOne: ['method_call']

Metrics/MethodLength:
  Enabled: true
  Max: 30
  CountAsOne: ['method_call']
