version: '3.8'

services:
  app:
    build: .
    container_name: onetime
    depends_on:
      - redis
    environment:
      ONETIMESECRET_REDIS_URL: redis://redis:6379
      ONETIMESECRET_SSL: false
      ONETIMESECRET_SECRET: CHANGEME
      ONETIMESECRET_HOST: localhost:3000
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app


  redis:
    image: redis:7.0-alpine
    container_name: onetime-redis
    volumes:
      - redis-data:/data

volumes:
  redis-data:
