name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey thanks for taking the time to create an issue -- @delano"
        pr-message: "Sweet, thanks for the PR. Ping me here if you need anything -- @delano"
