name: Ruby CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['3.2.0', '3.1.4', '3.0', '2.7', '2.6']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run tryouts
        run: bundle exec try
        continue-on-error: true
