name: Ruby CI

on:
  push:
    branches:
      - fix/*
      - rel/*
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch: # Allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - ruby: '3.2.0'
            bundler: '3.0.0'
          - ruby: '3.1.4'
            bundler: '3.0.0'
          - ruby: '3.0'
            bundler: '2.4.22'
          - ruby: '2.7'
            bundler: '2.4.22'
          - ruby: '2.6'
            bundler: '2.4.22'



    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install dependencies (bundler ${{ matrix.bundler }})
        run: |
          gem install bundler --version ${{ matrix.bundler }}
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run tryouts
        run: bundle exec try
        continue-on-error: true
